version: '3.8'

services:
  freshTour-client:
    container_name: freshTour-client
    restart: always
    image: node:20.10.0
    ports:
      - '4000:3000' # 리스트 형식으로 수정
    environment: 
      PORT: 3000

    volumes:
      - ./:/usr/src/freshTour-client
    working_dir: /usr/src/freshTour-client

    networks:
      - client-network # 리스트 형식으로 수정

    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
